# Site
name: "vannucherum.com"
title: "vannucherum.com"
description: "Inspired by the great dialogue from the Malayalam movie \"പുതിയ മുഖം\" - Articles about education, technology and travel"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
# google_analytics: 'UA-46278016-1'
disqus: 'vannucherum'
mailchimp-list: 'https://vannucherum.us8.list-manage.com/subscribe/post?u=0b3a73487c38ed4077b470a04&amp;id=7dc0240f5e'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  spacepirate:
    name: Vishnu Gp
    display_name: spacepirate
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: hello@vannucherum.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-analytics
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
# Jekyll-analytics Matomo    
jekyll_analytics:
  Matomo:
    url: mato.vannucherum.com
    siteId: "1"
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
